### PR TITLE
fix invalid account imports

### LINKED ISSUE #574: App crashes when Ethereum accounts are present in the account list
This is most probably linked to an Ethereum account present in my account list.

To reproduce with talisman/subwallet create an ethereum account. Note that the pjs extension also supports them, but only when importing from a JSON (that was exported from e.g talisman/subwallet).

When I want to connect the extension it crashes
> with Unexpected Application Error! Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

image

### PR DESCRIPTION
**Pull request by hamidra**
fixes #574

### CODE REVIEW

File: src/contexts/Account.tsx [hunk 1]
```diff
@@ -3,6 +3,10 @@ import type { SigningAccount } from '../types';
 import React, { useContext, createContext, useState, useEffect } from 'react';
 import { extractChainInfo, useAppLifeCycle } from '../lifecycle/index.js';
 import { useWallets } from './Wallets.js';
+import {
+  isSubstrateAccount,
+  isAccountAllowedOnChain,
+} from 'src/utils/polkadot-api';
```
Comment (jeluard) [inline src/contexts/Account.tsx:9]: Could you change this import to use relative path?

**Review by jeluard — CHANGES_REQUESTED** [review]
